# Generated by Django 2.0.6 on 2018-06-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilesandtasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tile',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='tilesandtasks.Tiles'),
            preserve_default=False,
        ),
    ]
