# Generated by Django 2.0.6 on 2018-06-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilesandtasks', '0002_tasks_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tilesandtasks.Tiles'),
        ),
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together={('tile', 'order')},
        ),
    ]
